# Generated by Django 4.0.6 on 2022-07-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='reference_number',
            new_name='ref',
        ),
    ]
