# Generated by Django 4.1 on 2022-08-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_reference_number_payment_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
