# Generated by Django 4.0.6 on 2022-07-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxd', '0005_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
