# Generated by Django 4.0.6 on 2022-07-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxd', '0006_career_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='black_friday',
            field=models.BooleanField(default=False),
        ),
    ]
