# Generated by Django 4.0.6 on 2022-07-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxd', '0007_product_black_friday'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='gift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='new_arrival',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='summer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='travels',
            field=models.BooleanField(default=False),
        ),
    ]
