# Generated by Django 4.1 on 2022-08-13 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dxd', '0010_remove_investor_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investor',
            options={'verbose_name_plural': 'Investor Site'},
        ),
    ]
