# Generated by Django 4.1 on 2022-08-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxd', '0013_homepagecarousel_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
