# Generated by Django 4.0.6 on 2022-07-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='braintree_id',
            new_name='paystack_ref_id',
        ),
    ]
