# Generated by Django 4.0.6 on 2022-07-14 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_braintree_id_order_paystack_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paystack_ref_id',
        ),
    ]
