# Generated by Django 4.0.6 on 2022-07-14 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_order_paystack_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='lineitem_total',
        ),
    ]
