# Generated by Django 4.0.6 on 2022-07-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
