# Generated by Django 4.0.6 on 2022-08-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('pay_on_delivery', 'Cash on delivery')], default='paystack', max_length=20),
        ),
    ]
