# Generated by Django 4.0.6 on 2022-08-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_remove_order_order_total_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('choose', 'Please select a Payment Option'), ('paystack', 'Paystack'), ('pay_on_delivery', 'Pay on delivery')], default='choose', max_length=20),
        ),
    ]
