# Generated by Django 4.0.6 on 2022-08-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_method',
            new_name='payment_option',
        ),
    ]
