# Generated by Django 4.0.6 on 2022-08-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_rename_payment_method_order_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('pay_on_delivery', 'Pay on delivery')], default='paystack', max_length=20),
        ),
    ]
